### ISSUE TITLE
help for datas

### ISSUE THREAD

**Issue by lihongyi1234** [yaxinus/santander-product-recommendation-8th-place#1]
hello, your work have an deep impression on my mind, I am appreciate your train of thought on this question, i am new to machine learning and data procession, but i can't get the data now, would you please send me the datas if you are not busy, if possible,i an looking forward to your reply.

**Comment by palevas** [comment]
You can still download it on competition site:
https://www.kaggle.com/c/santander-product-recommendation/data

**Comment by lihongyi1234** [comment]
I  tried  yesterday but unfortunately failed, becuase my phone number is not effective for downloading the data, and the datas seems too old that I can't find through the google , so i ask for your help, I am really insteresed in this question, if you are not busy, would you please send the data through E-mail，if OK, please reply me thanks, I am looking forward  to your letter soon, we can also talk about mechine learnng and data analysis in the future
